### ISSUE TITLE
Crash with mod Rubidium 1.19.2-0.6.1

### ISSUE THREAD

**Issue by MstDominik** [Harleyoc1/ChunkAnimator#30] opened 2022-08-15 10:07 UTC
[crash-2022-08-15_15.06.09-client.txt](https://github.com/Harleyoc1/ChunkAnimator/files/9336520/crash-2022-08-15_15.06.09-client.txt)
 check out this crash text i hope it helped

**Comment by Harleyoc1** [comment] 2022-08-21 10:27
Duplicate of #24

**Closed as not planned by Harleyoc1** 2022-08-21 10:27 UTC
Labels: bug
