### ISSUE TITLE
[1.20.1 Forge] Crash on startup 

### ISSUE THREAD

**Issue by MrKashew** [Harleyoc1/ChunkAnimator#38] opened 2023-08-28 08:39 UTC
[crash-2023-08-28_01.38.18-client.txt](https://github.com/Harleyoc1/ChunkAnimator/files/12452506/crash-2023-08-28_01.38.18-client.txt)

**Comment by Harleyoc1** [comment] 2023-09-02 08:50
This is due to incompatibility with Rubidium. Duplicate of #24

**Closed as completed by Harleyoc1** 2023-09-02 08:50 UTC
Labels: bug
