### ISSUE TITLE
Mixin crash using forge 1.20.1 and several other mods

### ISSUE THREAD

**Issue by Lothrazar** [Harleyoc1/ChunkAnimator#37] opened 2023-07-19 06:54 UTC
**Notice**
If you are opening an issue **for any other reason** than to report a bug or request a new feature, you should probably be using the [Discussions](https://github.com/Harleyoc1/Chunk-Animator/discussions) tab.

**Describe the bug**
Install the mod, start the game, crash log while loading about 
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [chunkanimator.mixins.json:LevelRendererMixin] from phase [DEFAULT] in config [chunkanimator.mixins.json] FAILED during APPLY`

**To Reproduce**
1. Have '...’ installed
2. Do ‘...’
3. See error

**Expected Behavior**

**Screenshots**

**Versions:**
 - Minecraft Version: [e.g. 1.16.5]  1.20.1
 - Forge Version: [e.g. 36.0.31] 47.1.3
 - Chunk Animator Version: [e.g. 2.1]  ChunkAnimator-1.20.1-1.3.7

**Additional context**

Crash log: https://pastebin.com/HtL4KayW

Mod list https://pastebin.com/W9Vs6nhX

Possibly incompatible with other mods using mixin like oculus 
using above modlist, removed chunk animator and the game could start up and no longer crashed

**Comment by Harleyoc1** [comment] 2023-08-13 09:42
Duplicate of #24

**Closed as completed by Harleyoc1** 2023-08-13 09:42 UTC
Labels: bug
