### ISSUE TITLE
crash with java update told to report it to here

### ISSUE THREAD

**Issue by GRKTheGreat** [Harleyoc1/ChunkAnimator#29] opened 2022-08-09 18:10 UTC
**Notice**
If you are opening an issue **for any other reason** than to report a bug or request a new feature, you should probably be using the [Discussions](https://github.com/Harleyoc1/Chunk-Animator/discussions) tab.

**Describe the bug**

**To Reproduce**
1. Have mod installed, latest java installed installed
2. Do try to boot mc
3. crash without loading MC

**Expected Behavior**
Really fast crash

**Screenshots**

**Versions:**
 - Minecraft Version: 1.18.2
 - Forge Version: 40.1.73
 - Chunk Animator Version: 1.3.4

**Additional context**
log https://paste.ee/p/ix0ZQ

Latest https://paste.ee/p/oY4fP

**Comment by Harleyoc1** [comment] 2022-08-09 22:18
Duplicate of #25

**Closed as completed by Harleyoc1** 2022-08-09 22:18 UTC
Labels: bug
